spring:
  zipkin:
    base-url: http://localhost:9411  #zipkin服务端的地址
  sleuth:
    sampler:
    probability: 1.0 #采样比例，设置为1.0时代表全部强求都需要采样
  profiles:
    active: dev
management:
  endpoints:
    web:
      cors:
        allowed-methods: '*'
feign:
  sentinel:
    enabled: true
  hystrix:
    enabled: false